//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMarketing
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractMar
    {
        public int id_Contract { get; set; }
        public Nullable<int> id_Client { get; set; }
        public string Number_Contract { get; set; }
        public string Date_Creation { get; set; }
        public string Date_Execution { get; set; }
        public Nullable<int> id_Status_Payment { get; set; }
        public string Detail_Order { get; set; }
        public Nullable<int> id_Status_Order { get; set; }
        public Nullable<int> id_Service { get; set; }
    
        public virtual ClientM ClientM { get; set; }
        public virtual ServiceMar ServiceMar { get; set; }
        public virtual StatusContractMar StatusContractMar { get; set; }
        public virtual StatusPaymentMar StatusPaymentMar { get; set; }
    }
}
